services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - curl -L https://github.com/docker/machine/releases/download/v0.10.0/docker-machine-`uname -s`-`uname -m` >/tmp/docker-machine
  - chmod +x /tmp/docker-machine
  - sudo mv /tmp/docker-machine /usr/local/bin/docker-machine
  - openssl aes-256-cbc -K $encrypted_8328c6c6f6cb_key -iv $encrypted_8328c6c6f6cb_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
#  - docker-machine create --driver generic --generic-ip-address 178.62.51.156 --generic-ssh-user root simple-prepaid-card
#  - eval "$(docker-machine env simple-prepaid-card)"

script:
   - echo "Deploy"
#  - make deploy
