version: '3'

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: php-fpm/php_fpm.dockerfile
    links:
      - redis
    volumes:
      - simple-prepaid-card:/simple-prepaid-card

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/nginx.dockerfile
    ports:
      - "80:8000"
    volumes:
      - simple-prepaid-card:/simple-prepaid-card
    links:
        - php-fpm

  redis:
    container_name: redis
    image: redis

volumes:
    simple-prepaid-card: